services:
  - type: web
    name: detection-lab-api
    runtime: python
    rootDir: backend
    buildCommand: pip install flask flask-cors requests gunicorn
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free